# Generated by Django 4.0.3 on 2022-04-07 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fit', '0003_remove_appointment_appointment_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointment',
            new_name='Appoint',
        ),
    ]
