# Generated by Django 4.0.3 on 2022-04-14 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fit', '0004_rename_appointment_appoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='prescription',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Fit.appoint'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='diagnosis',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Fit.doctor'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Fit.patient'),
        ),
    ]
