# Generated by Django 4.0.4 on 2022-04-21 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fit', '0005_visit_prescription_alter_visit_appointment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appoint',
            name='patient_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='patient_name',
        ),
    ]
