# Generated by Django 4.0.3 on 2022-04-21 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fit', '0006_remove_appoint_patient_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoint',
            name='doctor_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Fit.doctor'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctor_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
