# Generated by Django 4.0.3 on 2022-04-21 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fit', '0007_alter_appoint_doctor_name_alter_doctor_doctor_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appoint',
            name='doctor_name',
        ),
    ]
