# Generated by Django 4.0.4 on 2022-05-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit', '0009_appoint_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appoint',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
