# Generated by Django 4.0.4 on 2022-05-02 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fit', '0010_appoint_created_at_appoint_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appoint',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='appoint',
            name='updated_at',
        ),
    ]
