# Generated by Django 4.0.3 on 2022-05-02 11:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Fit', '0011_remove_appoint_created_at_remove_appoint_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 5, 2, 11, 36, 48, 325279, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appoint',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
