# Generated by Django 4.0.3 on 2022-05-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit', '0013_doctorprofile_userprofile_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
