# Generated by Django 4.0.3 on 2022-05-09 16:28

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Fit', '0016_alter_doctor_phone_number_alter_patient_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default=True, max_length=128, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default=True, max_length=128, region=None, unique=True),
        ),
    ]
