# Generated by Django 4.0.3 on 2022-05-09 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fit', '0019_alter_doctor_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='phone_number',
        ),
    ]
