# Generated by Django 4.0.3 on 2022-05-09 18:39

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Fit', '0020_remove_patient_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default=True, max_length=128, region=None),
        ),
    ]
