# Generated by Django 4.0.3 on 2022-06-07 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fit', '0022_alter_patient_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dentist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dentist_name', models.CharField(max_length=100, null=True)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(max_length=5, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='DentistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dentist', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Fit.dentist')),
            ],
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='doctor',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='DoctorProfile',
        ),
        migrations.AddField(
            model_name='visit',
            name='dentist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Fit.dentist'),
        ),
    ]
